import Dashboard from '@/components/Dashboard'
import './globals.css'
import { Inter } from 'next/font/google'
import Navbar from '@/components/Navbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className=''>
       <main className='flex'>
        <div className=''>
        <Dashboard/>
        </div>
      <div className='flex flex-col w-full bg-slate-100'>
      <Navbar/>
       {children}

      </div>
       </main>
       
      </body>
    </html>
  )
}
